#!/usr/bin/env bash

if
  [[ -s "/Users/johnson/.rvm/gems/ruby-2.2.2@global/environment" ]]
then
  source "/Users/johnson/.rvm/gems/ruby-2.2.2@global/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/johnson/.rvm/gems/ruby-2.2.2@global/environment'" >&2
  exit 1
fi
